"""资源归属与密级字段 —— Phase 3D 阶段1（docs/enterprise-rbac-plan.md 9.5）

`agent`/`skill` 补 `organization_id`/`team_id`（跟 `knowledge_spaces` 一样，可空 FK，
由后端按当前用户/目标 team 计算写入，不接受前端传值）+ `scope_type`/`sensitivity`；
`knowledge_spaces` 的 organization_id/team_id 在 20260924_0002 已经有了，这里只补
`scope_type`/`sensitivity` 两列。

`scope_type`：personal / department / enterprise（默认 personal，存量资源都是个人的）。
`sensitivity`：public / internal / confidential / restricted（默认 internal）。

不含数据回填：新列全部有 server_default，存量行直接落 personal/internal，不需要按
现有 team_id 反推——阶段1只是"加字段"，把已有资源按部门重新分类是阶段2 统一授权层
接入之后由业务操作触发的事，不是这次 schema 迁移的范围。

Revision ID: 20260927_0001
Revises: 20260924_0002
Create Date: 2026-09-27
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260927_0001'
down_revision: Union[str, Sequence[str], None] = '20260924_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('agent', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('agent', sa.Column('scope_type', sa.String(length=20), server_default='personal', nullable=False))
    op.add_column('agent', sa.Column('sensitivity', sa.String(length=20), server_default='internal', nullable=False))
    op.create_index('idx_agent_org', 'agent', ['organization_id'], unique=False)
    op.create_index('idx_agent_team', 'agent', ['team_id'], unique=False)
    op.create_foreign_key('fk_agent_org', 'agent', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_agent_team', 'agent', 'teams', ['team_id'], ['id'])

    op.add_column('skill', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('scope_type', sa.String(length=20), server_default='personal', nullable=False))
    op.add_column('skill', sa.Column('sensitivity', sa.String(length=20), server_default='internal', nullable=False))
    op.create_index('idx_skill_org', 'skill', ['organization_id'], unique=False)
    op.create_index('idx_skill_team', 'skill', ['team_id'], unique=False)
    op.create_foreign_key('fk_skill_org', 'skill', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_skill_team', 'skill', 'teams', ['team_id'], ['id'])

    op.add_column('knowledge_spaces', sa.Column('scope_type', sa.String(length=20), server_default='personal', nullable=False))
    op.add_column('knowledge_spaces', sa.Column('sensitivity', sa.String(length=20), server_default='internal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_spaces', 'sensitivity')
    op.drop_column('knowledge_spaces', 'scope_type')

    op.drop_constraint('fk_skill_team', 'skill', type_='foreignkey')
    op.drop_constraint('fk_skill_org', 'skill', type_='foreignkey')
    op.drop_index('idx_skill_team', table_name='skill')
    op.drop_index('idx_skill_org', table_name='skill')
    op.drop_column('skill', 'sensitivity')
    op.drop_column('skill', 'scope_type')
    op.drop_column('skill', 'team_id')
    op.drop_column('skill', 'organization_id')

    op.drop_constraint('fk_agent_team', 'agent', type_='foreignkey')
    op.drop_constraint('fk_agent_org', 'agent', type_='foreignkey')
    op.drop_index('idx_agent_team', table_name='agent')
    op.drop_index('idx_agent_org', table_name='agent')
    op.drop_column('agent', 'sensitivity')
    op.drop_column('agent', 'scope_type')
    op.drop_column('agent', 'team_id')
    op.drop_column('agent', 'organization_id')
    # ### end Alembic commands ###
