"""中央 Agent 受控路由字段 —— Phase 3D 阶段3（docs/enterprise-rbac-plan.md 9.5）。

`agent.agent_type`（central/department/personal，默认 personal）+
`agent.department_code`（hr/procurement/sales/finance/it，可空）。只加字段，
路由逻辑在 service/runtime/central_router.py，不在数据库层做约束。

Revision ID: 20260927_0003
Revises: 20260927_0002
Create Date: 2026-09-27
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260927_0003'
down_revision: Union[str, Sequence[str], None] = '20260927_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('agent_type', sa.String(length=20), server_default='personal', nullable=False))
    op.add_column('agent', sa.Column('department_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'department_code')
    op.drop_column('agent', 'agent_type')
    # ### end Alembic commands ###
