"""审批单 + 通用审计表 + 乐观锁/发布生命周期字段 —— Phase 3D 阶段4/5/6
（docs/enterprise-rbac-plan.md 9.5）。

新表 `approval_request`（阶段4，绑定具体 action+resource 的审批单）、`audit_event`
（阶段6，通用追加式审计——跟已有的 `kb_audit_log` 是两张表，那张是知识库空间模块
早先自己建的，范围只到 space/document/member/binding，这张给它覆盖不到的操作用，
不是把那张泛化）。

`agent`/`skill` 补 `row_version`/`lifecycle_status`，`knowledge_spaces` 只补
`row_version`（空间已经有 status 字段管 active/archived，不需要 draft/published
那一套）。阶段5这一步只加字段，不接比对/强制逻辑，见模型里的注释。

Revision ID: 20260927_0002
Revises: 20260927_0001
Create Date: 2026-09-27
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260927_0002'
down_revision: Union[str, Sequence[str], None] = '20260927_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], name='fk_approval_applicant'),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], name='fk_approval_approver'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_applicant', 'approval_request', ['applicant_id'], unique=False)
    op.create_index('idx_approval_resource', 'approval_request',
                     ['resource_type', 'resource_id', 'action', 'status'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_event_resource', 'audit_event',
                     ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_index('idx_audit_event_user', 'audit_event', ['user_id', 'created_at'], unique=False)

    op.add_column('agent', sa.Column('row_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent', sa.Column('lifecycle_status', sa.String(length=20), server_default='draft', nullable=False))

    op.add_column('skill', sa.Column('row_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skill', sa.Column('lifecycle_status', sa.String(length=20), server_default='draft', nullable=False))

    op.add_column('knowledge_spaces', sa.Column('row_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_spaces', 'row_version')

    op.drop_column('skill', 'lifecycle_status')
    op.drop_column('skill', 'row_version')

    op.drop_column('agent', 'lifecycle_status')
    op.drop_column('agent', 'row_version')

    op.drop_index('idx_audit_event_user', table_name='audit_event')
    op.drop_index('idx_audit_event_resource', table_name='audit_event')
    op.drop_table('audit_event')

    op.drop_index('idx_approval_resource', table_name='approval_request')
    op.drop_index('idx_approval_applicant', table_name='approval_request')
    op.drop_table('approval_request')
    # ### end Alembic commands ###
