"""enterprise rbac tables —— Phase 3B（docs/enterprise-rbac-plan.md）

organizations/teams 加 status 列 + 真实外键约束；新建 enterprise_role（角色目录，
数据在本迁移里种好）、organization_members、team_members 三张表；knowledge_spaces
的 team_id/organization_id 补真实外键（现有数据全是 NULL，不会因为脏数据加约束失败）。

不含"默认企业 + 现有用户批量入会"这一步数据回填——那是运营性质的一次性脚本，
不是 schema 迁移，见 scripts/backfill_default_organization.py（幂等，可重复跑）。

Revision ID: 20260924_0002
Revises: 20260924_0001
Create Date: 2026-09-24
"""

from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260924_0002'
down_revision: Union[str, Sequence[str], None] = '20260924_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# scope=organization: owner(3) / admin(2) / auditor(1) / member(0)
# scope=team:         admin(2) / editor(1) / member(0)
# rank 用于"至少要有 X 级"的判断，不用在代码里列举所有可能的角色名（见设计稿 1.2 节）。
_ENTERPRISE_ROLE_SEED = [
    {"scope": "organization", "code": "owner", "name": "企业所有者", "rank": 3},
    {"scope": "organization", "code": "admin", "name": "企业管理员", "rank": 2},
    {"scope": "organization", "code": "auditor", "name": "企业审计员", "rank": 1},
    {"scope": "organization", "code": "member", "name": "企业成员", "rank": 0},
    {"scope": "team", "code": "admin", "name": "部门管理员", "rank": 2},
    {"scope": "team", "code": "editor", "name": "部门编辑", "rank": 1},
    {"scope": "team", "code": "member", "name": "部门成员", "rank": 0},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_enterprise_role_scope_code', 'enterprise_role', ['scope', 'code'], unique=True)

    enterprise_role_table = sa.table(
        'enterprise_role',
        sa.column('scope', sa.String),
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('rank', sa.Integer),
        sa.column('created_at', sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(enterprise_role_table, [{**row, "created_at": now} for row in _ENTERPRISE_ROLE_SEED])

    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_om_org'),
    sa.ForeignKeyConstraint(['role_id'], ['enterprise_role.id'], name='fk_om_role'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_om_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_member_user', 'organization_members', ['user_id'], unique=False)
    op.create_index('uq_org_member', 'organization_members', ['organization_id', 'user_id'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['enterprise_role.id'], name='fk_tm_role'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_tm_team'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_tm_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_member_user', 'team_members', ['user_id'], unique=False)
    op.create_index('uq_team_member', 'team_members', ['team_id', 'user_id'], unique=True)
    op.create_foreign_key('fk_kspace_team', 'knowledge_spaces', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('fk_kspace_org', 'knowledge_spaces', 'organizations', ['organization_id'], ['id'])
    op.add_column('organizations', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('teams', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.create_foreign_key('fk_team_org', 'teams', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_team_org', 'teams', type_='foreignkey')
    op.drop_column('teams', 'status')
    op.drop_column('organizations', 'status')
    op.drop_constraint('fk_kspace_org', 'knowledge_spaces', type_='foreignkey')
    op.drop_constraint('fk_kspace_team', 'knowledge_spaces', type_='foreignkey')
    op.drop_index('uq_team_member', table_name='team_members')
    op.drop_index('idx_team_member_user', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('uq_org_member', table_name='organization_members')
    op.drop_index('idx_org_member_user', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index('uq_enterprise_role_scope_code', table_name='enterprise_role')
    op.drop_table('enterprise_role')
    # ### end Alembic commands ###
