"""trusted baseline —— Phase 3A：对着全新空库用 alembic revision --autogenerate 生成，
覆盖当前 Base.metadata 声明的完整结构（38 张表）。取代原来 20260830_0001~20260923_0008
这条从未被真正执行过的链（历史文件搬到 migrations/_old_versions_for_squash/，不再参与
alembic upgrade，仅作存档）。

user <-> agent 有一对互相引用的外键，autogenerate 生成的原始顺序有问题，已手动调整
建表/删表顺序（见 upgrade()/downgrade() 里的注释）。验证方式：在全新空库跑完
upgrade head 后再跑一次 autogenerate，diff 为空，确认跟 Base.metadata 完全一致。

Revision ID: 20260924_0001
Revises:
Create Date: 2026-09-24
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


revision: str = '20260924_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 手动调整：user <-> agent 是一对互相引用的外键（user.selected_agent_id -> agent.id，
    # agent.user_id -> user.id），autogenerate 生成的原始顺序会先建 agent 表、
    # 引用一个还不存在的 user 表而报错。create_all() 在实际运行时能处理这种循环依赖
    # （拆成两步），但 Alembic 的建表脚本要手动拆：先建 user（不带 selected_agent_id
    # 的外键约束），再建 agent，最后单独把 fk_user_selected_agent 加回去。
    op.create_table('kb_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_audit_space_time', 'kb_audit_log', ['space_id', 'created_at'], unique=False)
    op.create_index('idx_kb_audit_user', 'kb_audit_log', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('price_desc', sa.String(length=200), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('skill_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('config_text', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skill_version_skill', 'skill_version', ['skill_id', 'version_no'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_org', 'teams', ['organization_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_disabled', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('auth_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('selected_agent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt_file', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('rag_enabled', sa.Integer(), nullable=True),
    sa.Column('memory_enabled', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('kb_top_k', sa.Integer(), nullable=False),
    sa.Column('kb_rerank_enabled', sa.Integer(), nullable=False),
    sa.Column('kb_force_citation', sa.Integer(), nullable=False),
    sa.Column('kb_refuse_when_empty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_agent_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_user_id_id', 'agent', ['user_id', 'id'], unique=False)
    op.create_foreign_key('fk_user_selected_agent', 'user', 'agent', ['selected_agent_id'], ['id'])
    op.create_table('agent_api_connector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('headers_encrypted', sa.Text(), nullable=True),
    sa.Column('param_schema_json', sa.Text(), nullable=False),
    sa.Column('static_query_json', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_api_connector_agent'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_api_connector_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_api_connector_agent', 'agent_api_connector', ['agent_id'], unique=False)
    op.create_table('agent_pipeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_pipeline_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_pipeline_user', 'agent_pipeline', ['user_id'], unique=False)
    op.create_table('background_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_task_agent'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['background_task.id'], name='fk_task_parent'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_task_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_background_task_status_started', 'background_task', ['status', 'started_at'], unique=False)
    op.create_index('idx_background_task_status_type_created', 'background_task', ['status', 'task_type', 'created_at', 'id'], unique=False)
    op.create_index('idx_background_task_status_type_next_run', 'background_task', ['status', 'task_type', 'next_run_at', 'created_at', 'id'], unique=False)
    op.create_index('idx_background_task_user_status_created', 'background_task', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_background_task_user_type_created', 'background_task', ['user_id', 'task_type', 'created_at'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_user_agent_time', 'chat', ['user_id', 'agent_id', 'create_time'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_pinned', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_conv_agent'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_conv_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_user_agent_flags_time', 'conversation', ['user_id', 'agent_id', 'is_archived', 'is_pinned', 'update_time'], unique=False)
    op.create_index('idx_conversation_user_time', 'conversation', ['user_id', 'update_time'], unique=False)
    op.create_table('knowledge_spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('purpose', sa.String(length=60), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('health_json', sa.Text(), nullable=True),
    sa.Column('legacy_agent_id', sa.Integer(), nullable=True),
    sa.Column('vector_migrated', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_kspace_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kspace_org', 'knowledge_spaces', ['organization_id'], unique=False)
    op.create_index('idx_kspace_team', 'knowledge_spaces', ['team_id'], unique=False)
    op.create_index('idx_kspace_user_status', 'knowledge_spaces', ['user_id', 'status'], unique=False)
    op.create_table('llm_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_config_user_active', 'llm_config', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_llm_config_user_model', 'llm_config', ['user_id', 'model_name'], unique=False)
    op.create_table('memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chat_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_memory_agent'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_memory_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_agent_id', 'memory', ['agent_id'], unique=False)
    op.create_index('idx_memory_user_agent_type_created', 'memory', ['user_id', 'agent_id', 'memory_type', 'created_at'], unique=False)
    op.create_table('notification_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('webhook_url', sa.String(length=1000), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_notification_channel_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_channel_user', 'notification_channel', ['user_id'], unique=False)
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_operation_log_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operation_log_created', 'operation_log', ['created_at'], unique=False)
    op.create_index('idx_operation_log_latency_created', 'operation_log', ['latency_ms', 'created_at'], unique=False)
    op.create_index('idx_operation_log_method_created', 'operation_log', ['method', 'created_at'], unique=False)
    op.create_index('idx_operation_log_status_created', 'operation_log', ['status_code', 'created_at'], unique=False)
    op.create_index('idx_operation_log_user_created', 'operation_log', ['user_id', 'created_at'], unique=False)
    op.create_table('rag_debug_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('space_ids_json', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('rerank_enabled', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('in_eval_set', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_rds_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rds_space', 'rag_debug_samples', ['space_id'], unique=False)
    op.create_index('idx_rds_user_created', 'rag_debug_samples', ['user_id', 'created_at'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('config_file', sa.String(length=500), nullable=False),
    sa.Column('is_public', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skill_public', 'skill', ['is_public'], unique=False)
    op.create_index('idx_skill_user_id', 'skill', ['user_id'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('persona', sa.String(length=50), nullable=True),
    sa.Column('extra_info', sa.Text(), nullable=True),
    sa.Column('auto_summary', sa.Text(), nullable=True),
    sa.Column('last_inferred_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_profile_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_profile_user_id', 'user_profile', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name='fk_subscription_plan'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_subscription_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_widgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('data_source_json', sa.Text(), nullable=True),
    sa.Column('processor_json', sa.Text(), nullable=True),
    sa.Column('view_json', sa.Text(), nullable=True),
    sa.Column('trigger_json', sa.Text(), nullable=True),
    sa.Column('actions_json', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_alert_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_widgets_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_widgets_next_run', 'user_widgets', ['enabled', 'next_run_at'], unique=False)
    op.create_index('idx_user_widgets_user_sort', 'user_widgets', ['user_id', 'sort_order'], unique=False)
    op.create_table('user_workspace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modules_json', sa.Text(), nullable=False),
    sa.Column('widgets_json', sa.Text(), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_workspace_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_workspace_user_id', 'user_workspace', ['user_id'], unique=False)
    op.create_table('web_monitor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(length=30), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.Column('last_title', sa.String(length=255), nullable=True),
    sa.Column('last_excerpt', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_change_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_web_monitor_agent'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_web_monitor_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_web_monitor_user_active', 'web_monitor', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_web_monitor_user_checked', 'web_monitor', ['user_id', 'last_checked_at'], unique=False)
    op.create_table('agent_knowledge_space',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_aks_agent'),
    sa.ForeignKeyConstraint(['space_id'], ['knowledge_spaces.id'], name='fk_aks_space'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aks_space', 'agent_knowledge_space', ['space_id'], unique=False)
    op.create_index('uq_agent_space', 'agent_knowledge_space', ['agent_id', 'space_id'], unique=True)
    op.create_table('agent_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_run_agent'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='fk_run_chat'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='fk_run_conv', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_run_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_run_agent_conversation_started', 'agent_run', ['agent_id', 'conversation_id', 'started_at'], unique=False)
    op.create_index('idx_agent_run_agent_started', 'agent_run', ['agent_id', 'started_at'], unique=False)
    op.create_index('idx_agent_run_status_started', 'agent_run', ['status', 'started_at'], unique=False)
    op.create_index('idx_agent_run_user_started', 'agent_run', ['user_id', 'started_at'], unique=False)
    op.create_table('agent_skill',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    op.create_table('eval_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cases_json', sa.Text(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_eval_set_agent'),
    sa.ForeignKeyConstraint(['space_id'], ['knowledge_spaces.id'], name='fk_eval_set_space'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_eval_set_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_set_user_created', 'eval_set', ['user_id', 'created_at'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='fk_knowledge_agent'),
    sa.ForeignKeyConstraint(['space_id'], ['knowledge_spaces.id'], name='fk_knowledge_space'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_knowledge_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_agent_created', 'knowledge', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_knowledge_agent_enabled_status', 'knowledge', ['agent_id', 'is_enabled', 'status'], unique=False)
    op.create_index('idx_knowledge_user_created', 'knowledge', ['user_id', 'created_at'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='fk_msg_conv'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_time', 'message', ['conversation_id', 'create_time'], unique=False)
    op.create_table('space_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['knowledge_spaces.id'], name='fk_sm_space'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_sm_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_space_member_user', 'space_members', ['user_id'], unique=False)
    op.create_index('uq_space_member', 'space_members', ['space_id', 'user_id'], unique=True)
    op.create_table('widget_data_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('ok', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['user_widgets.id'], name='fk_widget_data_points_widget'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_widget_data_points_widget_time', 'widget_data_points', ['widget_id', 'recorded_at'], unique=False)
    op.create_table('agent_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_args', sa.Text(), nullable=True),
    sa.Column('tool_result', sa.Text(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], name='fk_step_run'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_step_run_step', 'agent_step', ['run_id', 'step_no'], unique=False)
    op.create_table('eval_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eval_set_id', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('precision_at_k', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eval_set_id'], ['eval_set.id'], name='fk_eval_run_set'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_run_set_created', 'eval_run', ['eval_set_id', 'created_at'], unique=False)
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], name='fk_chunk_knowledge'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_chunk_knowledge_index', 'knowledge_chunk', ['knowledge_id', 'chunk_index'], unique=False)
    op.create_index('idx_knowledge_chunk_vector_id', 'knowledge_chunk', ['vector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_knowledge_chunk_vector_id', table_name='knowledge_chunk')
    op.drop_index('idx_knowledge_chunk_knowledge_index', table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_index('idx_eval_run_set_created', table_name='eval_run')
    op.drop_table('eval_run')
    op.drop_index('idx_agent_step_run_step', table_name='agent_step')
    op.drop_table('agent_step')
    op.drop_index('idx_widget_data_points_widget_time', table_name='widget_data_points')
    op.drop_table('widget_data_points')
    op.drop_index('uq_space_member', table_name='space_members')
    op.drop_index('idx_space_member_user', table_name='space_members')
    op.drop_table('space_members')
    op.drop_index('idx_message_conversation_time', table_name='message')
    op.drop_table('message')
    op.drop_index('idx_knowledge_user_created', table_name='knowledge')
    op.drop_index('idx_knowledge_agent_enabled_status', table_name='knowledge')
    op.drop_index('idx_knowledge_agent_created', table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_index('idx_eval_set_user_created', table_name='eval_set')
    op.drop_table('eval_set')
    op.drop_table('agent_skill')
    op.drop_index('idx_agent_run_user_started', table_name='agent_run')
    op.drop_index('idx_agent_run_status_started', table_name='agent_run')
    op.drop_index('idx_agent_run_agent_started', table_name='agent_run')
    op.drop_index('idx_agent_run_agent_conversation_started', table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_index('uq_agent_space', table_name='agent_knowledge_space')
    op.drop_index('idx_aks_space', table_name='agent_knowledge_space')
    op.drop_table('agent_knowledge_space')
    op.drop_index('idx_web_monitor_user_checked', table_name='web_monitor')
    op.drop_index('idx_web_monitor_user_active', table_name='web_monitor')
    op.drop_table('web_monitor')
    op.drop_index('idx_user_workspace_user_id', table_name='user_workspace')
    op.drop_table('user_workspace')
    op.drop_index('idx_user_widgets_user_sort', table_name='user_widgets')
    op.drop_index('idx_user_widgets_next_run', table_name='user_widgets')
    op.drop_table('user_widgets')
    op.drop_table('user_subscription')
    op.drop_table('user_role')
    op.drop_index('idx_user_profile_user_id', table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_table('tool')
    op.drop_index('idx_skill_user_id', table_name='skill')
    op.drop_index('idx_skill_public', table_name='skill')
    op.drop_table('skill')
    op.drop_index('idx_rds_user_created', table_name='rag_debug_samples')
    op.drop_index('idx_rds_space', table_name='rag_debug_samples')
    op.drop_table('rag_debug_samples')
    op.drop_index('idx_operation_log_user_created', table_name='operation_log')
    op.drop_index('idx_operation_log_status_created', table_name='operation_log')
    op.drop_index('idx_operation_log_method_created', table_name='operation_log')
    op.drop_index('idx_operation_log_latency_created', table_name='operation_log')
    op.drop_index('idx_operation_log_created', table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index('idx_notification_channel_user', table_name='notification_channel')
    op.drop_table('notification_channel')
    op.drop_index('idx_memory_user_agent_type_created', table_name='memory')
    op.drop_index('idx_memory_agent_id', table_name='memory')
    op.drop_table('memory')
    op.drop_index('idx_llm_config_user_model', table_name='llm_config')
    op.drop_index('idx_llm_config_user_active', table_name='llm_config')
    op.drop_table('llm_config')
    op.drop_index('idx_kspace_user_status', table_name='knowledge_spaces')
    op.drop_index('idx_kspace_team', table_name='knowledge_spaces')
    op.drop_index('idx_kspace_org', table_name='knowledge_spaces')
    op.drop_table('knowledge_spaces')
    op.drop_index('idx_conversation_user_time', table_name='conversation')
    op.drop_index('idx_conversation_user_agent_flags_time', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('idx_chat_user_agent_time', table_name='chat')
    op.drop_table('chat')
    op.drop_index('idx_background_task_user_type_created', table_name='background_task')
    op.drop_index('idx_background_task_user_status_created', table_name='background_task')
    op.drop_index('idx_background_task_status_type_next_run', table_name='background_task')
    op.drop_index('idx_background_task_status_type_created', table_name='background_task')
    op.drop_index('idx_background_task_status_started', table_name='background_task')
    op.drop_table('background_task')
    op.drop_index('idx_agent_pipeline_user', table_name='agent_pipeline')
    op.drop_table('agent_pipeline')
    op.drop_index('idx_agent_api_connector_agent', table_name='agent_api_connector')
    op.drop_table('agent_api_connector')
    # 手动调整：跟 upgrade() 里的说明对应——先拆掉 user -> agent 的外键，
    # 再删 agent（此时没有别的表引用它了），最后删 user。
    op.drop_constraint('fk_user_selected_agent', 'user', type_='foreignkey')
    op.drop_index('idx_agent_user_id_id', table_name='agent')
    op.drop_table('agent')
    op.drop_table('user')
    op.drop_index('idx_team_org', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_skill_version_skill', table_name='skill_version')
    op.drop_table('skill_version')
    op.drop_table('role')
    op.drop_table('plan')
    op.drop_table('organizations')
    op.drop_index('idx_kb_audit_user', table_name='kb_audit_log')
    op.drop_index('idx_kb_audit_space_time', table_name='kb_audit_log')
    op.drop_table('kb_audit_log')
    # ### end Alembic commands ###
